name: ChangeDetection.io PIP package test

# Triggers the workflow on push or pull request events

# This line doesnt work, even tho it is the documented one
on: [push, pull_request]

  # Changes to requirements.txt packages and Dockerfile may or may not always be compatible with arm etc, so worth testing
  # @todo: some kind of path filter for requirements.txt and Dockerfile
jobs:
  test-pip-build-basics:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9


        - name: Test that the basic pip built package runs without error
          run: |
            mkdir dist                        
            python3 setup.py bdist_wheel            
            pip3 install -r requirements.txt
            rm ./changedetection.py
            pip3 install dist/changedetection.io*.whl
